:wrench: Clean up some comments etc

diff --git a/bin/capt b/bin/capt
--- a/bin/capt
+++ b/bin/capt
@@ -528,26 +528,23 @@ run_scripts () {
         dbg CAPT_FILES_CHANGED: $CAPT_FILES_CHANGED
         inv=( ${(@s: :)line} ) # split on spaces to get first, discard beyond second
         name=$inv[1]
-        # TODO(#1) failok mode
         # If name starts with - then remove it and treat the run as in fail-ok mode
         unset failok
-        if [[ $name[1] = '-' ]]; then
-            name=${name[2,$#name]} # remove first char
-            failok=1
-        fi
+        if [[ $name[1] = '-' ]]; then name=${name[2,$#name]}; failok=1; fi  # remove first char
         script=$inv[2]
         cmd=${line#* } # remove up to first space, keeping all the rest
         dbg "inv:" $inv[1] "::" $inv[2] "::" $inv[3] "::"
         cmd0=${cmd%% *} # keep only first part, the command name
         dbg "line: $line :: cmd0: $cmd0 :: cmd: $cmd"
 
+        # TODO Add special casing for specific hooks needing special treatment
+        if [[ $active_githook =~ 'commit-msg' ]]; then : ; fi
+
         # Built-in has filter already, or specified filter
-        # print_name=$(ssed 's/[:(].*//' <<<$name)
         print_name=$(print $name | ssed 's/[:(].*//' )
-        # print name: $print_name :: hooks: $black_triggers
-        if (( $black_triggers[(Ie)$print_name] )); then
-            aye "$fg[red]Snuffin’ out yer $print_name trigger since ye blacklisted the bedeviler (CAPT_BLACK_TRIGGERS).$reset_color"
-            continue
+        if (( $black_triggers[(Ie)$print_name] ))
+        then aye "$fg[red]Snuffin’ out yer $print_name trigger since ye blacklisted the bedeviler (CAPT_BLACK_TRIGGERS).$reset_color"
+             continue
         fi
         printf -v pending "$reset_color$fg_bold[blue]$icon$reset_color $fg[yellow]☠☠☠ %-${max_cmd_len}s$reset_color" ${(U)print_name}  # uskull
         # Built-in triggers are the only ones with no colon
@@ -555,50 +552,46 @@ run_scripts () {
         then dbg "built-in plain checker with no spec:" $name
              suit=♠
              pending="$pending$suit"
-            # Need to fix up cmd since no spec, and maybe include filtered files
-            script=$inv[1]
-            just_buitins=${(k)builtin_cannons}
-            if ! (($just_buitins[(Ie)$print_name])); then
-                print; aye "$fg[red]ERROR: Unable to find built-in trigger: $bold_color$print_name$reset_color"
-                exit 1
-            fi
+             # Need to fix up cmd since no spec, and maybe include filtered files
+             script=$inv[1]
+             just_buitins=${(k)builtin_cannons}
+             if ! (($just_buitins[(Ie)$print_name])); then
+                 print; aye "$fg[red]ERROR: Unable to find built-in trigger: $bold_color$print_name$reset_color"
+                 exit 1
+             fi
+             get_combined_filtereds || continue
+             cmd=$(print $dsl | ssed -r 's/^\([^)]+\)//')
+             cmd0=$(print $cmd | ssed -r 's/ .*//')
 
-            # TODO Add special casing for specific hooks needing special treatment
-            if [[ $active_githook =~ 'commit-msg' ]]; then : ; fi
-
-            get_combined_filtereds || continue
-            cmd=$(print $dsl | ssed -r 's/^\([^)]+\)//')
-            cmd0=$(print $cmd | ssed -r 's/ .*//')
-
-            print_filtereds $filtered_files
-            # Remove end of help and prep for printing on non-verbose
-            helpmsg=$( ssed -r 's/ \(.*\)//' <<< $builtin_helps[$print_name] )
-            if   [[ -n $CAPT_VERBOSE ]]
-            then aye "# $fg[yellow]$helpmsg$reset_color"
-                 aye "$suit $fg_bold[yellow]$cmd$reset_color" # spade, built-in
-            fi
+             print_filtereds $filtered_files
+             # Remove end of help and prep for printing on non-verbose
+             helpmsg=$( ssed -r 's/ \(.*\)//' <<< $builtin_helps[$print_name] )
+             if   [[ -n $CAPT_VERBOSE ]]
+             then aye "# $fg[yellow]$helpmsg$reset_color"
+                  aye "$suit $fg_bold[yellow]$cmd$reset_color" # spade, built-in
+             fi
 
         elif [[ $name == *\(*\)* ]]
         then dbg "custom-rigged filtered checker"
              suit=♥
              pending="$pending$suit"
-            get_combined_filtereds || continue
-            print_filtereds $filtered_files
+             get_combined_filtereds || continue
+             print_filtereds $filtered_files
         elif [[ $line == *CAPT_FILES_CHANGED* || ! $name == *: ]]
         then dbg "unfiltered checker"
              suit=♦
              print -n "$pending$suit"
-            filtered_files=( $CAPT_FILES_CHANGED )
-            if   [[ $#filtered_files < 1 ]] # FIXME Probably can never get here
-                 then print " ZZZ $pending ($suit Not seein any matchin files staged, skippin.) ZZZ" ; continue
-            else print_filtereds $CAPT_FILES_CHANGED
-                 print_cmd_and_help
-            fi
-        else # Ye took care of file selection yerself, or no files needin fer sayin.
-            suit=♣
-            print -n "$pending$suit"
-            print_filtereds ∞
-            print_cmd_and_help
+             filtered_files=( $CAPT_FILES_CHANGED )
+             if   [[ $#filtered_files < 1 ]] # FIXME Probably can never get here
+             then print " ZZZ $pending ($suit Not seein any matchin files staged, skippin.) ZZZ" ; continue
+             else print_filtereds $CAPT_FILES_CHANGED
+                  print_cmd_and_help
+             fi
+        else dbg 'no files, no filter'
+             suit=♣
+             print -n "$pending$suit"
+             print_filtereds ∞
+             print_cmd_and_help
         fi
 
         # Add args to pass from git if it's one of the arg-accepting hooks
